version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - media-files-volume:/usr/src/app/public/uploads
volumes:
  media-files-volume:
    driver: local
