version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - media-files-volume:/usr/src/app/frontend/uploads
      - recordings-volume:/usr/src/app/recordings
volumes:
  media-files-volume:
    driver: local
  recordings-volume:
    driver: local
